version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - persist_from_workspace:
          root: ~/repo
          paths:
            - android/app/build/outputs
      - run:
          name: Run Unit Tests
          command: react-native run-android --variant=debug && yarn test

workflows:
  test-only:
    jobs:
      - test:
          context:
            - main
