version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install --frozen-lockfile
      - run:
          name: Run tests
          command: |
            nvm use
            yarn run test

workflows:
  test-only:
    jobs:
      - test:
          context:
            - main
