version: 2.1
jobs:
  test:
    executor: equestria/linux
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test