version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.10.0
    steps:
      - run: echo "Say hello to YAML!"

workflows:
  test_only:
    jobs:
      - build
