version: 2.1

jobs:
  build:
    macos:
      xcode: "12.0.0"
    steps:
      - checkout
      - run: yarn
      - run: yarn test
      - run: yarn lint

workflows:
  build_and_test:
    jobs:
      - build
