version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - run: echo "Say hello to YAML!"

workflows:
  test_only:
    jobs:
      - test
