version: 2.1

jobs:
  test:
    executor: equestria/linux
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install --frozen-lockfile
      - run:
          name: Run tests
          command: |
            nvm use
            yarn run test
