version: 2.1
jobs:
  build:
    working_directory: ~/MyCircleCI
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test