version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.6-buster
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run:
          name: Build Android
          command: |
            cd android && ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apk