version: 2.1

jobs:
  build:
    working_directory: ~/MyCircleCI
    docker:
      - image: cimg/node:12.16
    steps:
      - run: echo "Say hello to YAML!"

workflows:
  test_only:
    jobs:
      - build
