version: 2.1
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Run Unit Tests
          command: react-native run-android --variant=debug && yarn test